### ISSUE TITLE
Chart customization

### ISSUE THREAD

**Issue by velthune** [99ff00/react-charty#3]
Hi Aleksandr,
first of all thanks for sharing this nice component, is great imho!

What if I would like to make corners more "smooth" on Line chart?
What if I would fill Line chart area? (with a gradient?)

It this possibile right now?

**Comment by 99ff00** [comment]
I'm sorry, I overlooked your submission and PR

> first of all thanks for sharing this nice component, is great imho!
Thanks for the kind words :)

> What if I would like to make corners more "smooth" on Line chart?
Hm... not possible for now as I use `lineTo` method to draw the line series. I'm afraid adding splines will add excessive complexity to the code and will slow down the animations. But if there will be more requests for splines I could add it.

> What if I would fill Line chart area? (with a gradient?)
Good idea. I just published next version with new `fillColors` prop, which also supports linear gradients (only for linear chart for now). Here's an example:
```
"fillColors": {
    "y0": { "type": "linear_gradient_v", "colors": ["#4BD964", "#4BD964", "#FFFFFF00"] },
    "y1": "#FE3C3011"
  },
```

... and as a little bonus, regular lines also support gradient now.
