### ISSUE TITLE
Can I have only the preview?

### ISSUE THREAD

**Issue by melalj** [99ff00/react-charty#5]
Heya,
Thanks for making this!
I'm looking to get only the preview without the main visualization.

<img width="818" alt="Screenshot 2020-03-01 11 18 14" src="https://user-images.githubusercontent.com/3869766/75623811-59f6b900-5bae-11ea-88dd-54f962ffb433.png">

Is it possible?

**Comment by 99ff00** [comment]
@melalj it's impossible at this moment but I can add `showChart` option. But first let's figure out another issue you posted.

**Comment by 99ff00** [comment]
@melalj I added two new props to control main area visibility `showMainArea` and brush controls `showBrush` in this release https://github.com/99ff00/react-charty/releases/tag/v0.1.6
Please try and let me know.
